title: "Slap Fingerprint Segmentation (SlapSeg) Evaluation"
description: "Supplemental information regarding NIST's Slap Fingerprint Segmentation Evaluation"
baseurl: "/slapseg"
rooturl: "https://pages.nist.gov"
